import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Barlow_Semi_Condensed } from "next/font/google";
import { Footer } from "./components/Footer";

const barlow = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Escolha os pesos que deseja usar
  variable: "--font-barlow", // Nome personalizado para a variável CSS
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Escolha os pesos que deseja usar
  variable: "--font-inter", // Nome personalizado para a variável CSS
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.variable} ${barlow.variable} overflow-x-hidden antialiased`}
      >
        <Header/>
        {children} 
        <Footer/>
      </body>
    </html>
  );
}
